<?php

declare(strict_types=1);

/**
 * Authoritative framework status transition matrix (certification closure).
 *
 * Encodes happy-path + failure/resume edges used by 3B engines.
 * Enforced by orange_restore_fw_transition() — does not alter engine algorithms.
 *
 * Requires restore_job_framework.php constants to be loaded first.
 */

const ORANGE_RESTORE_FW_TRANSITION_MATRIX_VERSION = '3B.4M-fw-transition-v1';

/**
 * Linear happy-path / common phase chains (from → to adjacent).
 *
 * @return list<list<string>>
 */
function orange_restore_fw_transition_chains(): array
{
    return [
        [
            ORANGE_RESTORE_FW_STATUS_QUEUED,
            ORANGE_RESTORE_FW_STATUS_PREPARING,
            ORANGE_RESTORE_FW_STATUS_WAITING_CONFIRMATION,
            ORANGE_RESTORE_FW_STATUS_DRY_RUNNING,
            ORANGE_RESTORE_FW_STATUS_DRY_COMPLETED,
            ORANGE_RESTORE_FW_STATUS_EXECUTION_PRECHECK,
            ORANGE_RESTORE_FW_STATUS_EXECUTION_PLAN_READY,
            ORANGE_RESTORE_FW_STATUS_AWAITING_FINAL_APPROVAL,
            ORANGE_RESTORE_FW_STATUS_APPROVED_WAITING_EXECUTION,
            ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_PENDING,
            ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_RUNNING,
            ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_READY,
            ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_PENDING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_RUNNING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_READY,
            ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFIED,
            ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_RUNNING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_READY,
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_PENDING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_RUNNING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_READY,
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_READY,
            ORANGE_RESTORE_FW_STATUS_MAINTENANCE_REQUESTED,
            ORANGE_RESTORE_FW_STATUS_MAINTENANCE_VALIDATING,
            ORANGE_RESTORE_FW_STATUS_MAINTENANCE_ACTIVE,
            ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_PENDING,
            ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_RUNNING,
            ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_READY,
            ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_PENDING,
            ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_RUNNING,
            ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_READY,
            ORANGE_RESTORE_FW_STATUS_RESTORE_FINALIZING,
            ORANGE_RESTORE_FW_STATUS_RESTORE_COMPLETED,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_READY,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_PENDING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_DATABASE_RUNNING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_DATABASE_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_FILES_RUNNING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_FILES_VERIFYING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_READY,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_FINALIZING,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_COMPLETED,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_READY,
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_PENDING,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_RUNNING,
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_WARNING,
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_MANUAL_REVIEW,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_READY,
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_MANUAL_REVIEW,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_MANUAL_REVIEW,
            ORANGE_RESTORE_FW_STATUS_MAINTENANCE_REQUESTED,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_MANUAL_REVIEW,
            ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_BLOCKED,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_RESTORE_COMPLETED,
            ORANGE_RESTORE_FW_STATUS_EXECUTION_COMPLETED,
            ORANGE_RESTORE_FW_STATUS_COMPLETED,
        ],
        [
            ORANGE_RESTORE_FW_STATUS_ROLLBACK_COMPLETED,
            ORANGE_RESTORE_FW_STATUS_EXECUTION_COMPLETED,
            ORANGE_RESTORE_FW_STATUS_COMPLETED,
        ],
    ];
}

/**
 * Extra non-linear edges (resume / branch).
 *
 * @return list<array{0:string,1:string}>
 */
function orange_restore_fw_transition_extra_edges(): array
{
    return [
        [ORANGE_RESTORE_FW_STATUS_DRY_RUNNING, ORANGE_RESTORE_FW_STATUS_DRY_FAILED],
        [ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_RUNNING, ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_FAILED],
        [ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_VERIFYING, ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_FAILED],
        [ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_FAILED, ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_PENDING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_RUNNING, ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_FAILED],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_VERIFYING, ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_FAILED],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_FAILED, ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_PENDING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFYING, ORANGE_RESTORE_FW_STATUS_SHADOW_NOT_READY],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_NOT_READY, ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFYING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_RUNNING, ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_FAILED],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_VERIFYING, ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_FAILED],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_FAILED, ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_RUNNING, ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_FAILED],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_FAILED, ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_PENDING],
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_RUNNING, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_FAILED],
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_VERIFYING, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_FAILED],
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_FAILED, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_PENDING],
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_FAILED, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_RUNNING, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_FAILED],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_VERIFYING, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_FAILED],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_FAILED, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_PENDING],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_FAILED, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_DATABASE_RUNNING, ORANGE_RESTORE_FW_STATUS_ROLLBACK_FAILED],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_FILES_RUNNING, ORANGE_RESTORE_FW_STATUS_ROLLBACK_FAILED],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_FAILED, ORANGE_RESTORE_FW_STATUS_ROLLBACK_PENDING],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_FAILED, ORANGE_RESTORE_FW_STATUS_ROLLBACK_DATABASE_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_MAINTENANCE_ACTIVE, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_PENDING, ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_PENDING, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_PENDING, ORANGE_RESTORE_FW_STATUS_ROLLBACK_DATABASE_RUNNING],
        // Skip-adjacent resumes used by engines after partial checkpoints.
        [ORANGE_RESTORE_FW_STATUS_PRODUCTION_IMPORT_READY, ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_UPLOADS_CUTOVER_READY, ORANGE_RESTORE_FW_STATUS_RESTORE_FINALIZING],
        [ORANGE_RESTORE_FW_STATUS_ROLLBACK_READY, ORANGE_RESTORE_FW_STATUS_ROLLBACK_FINALIZING],
        [ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_READY, ORANGE_RESTORE_FW_STATUS_MAINTENANCE_ACTIVE],
        [ORANGE_RESTORE_FW_STATUS_MAINTENANCE_REQUESTED, ORANGE_RESTORE_FW_STATUS_MAINTENANCE_ACTIVE],
        [ORANGE_RESTORE_FW_STATUS_APPROVED_WAITING_EXECUTION, ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_PRE_RESTORE_BACKUP_READY, ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_RESTORE_READY, ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFYING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_VERIFIED, ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_FILES_READY, ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_RUNNING],
        [ORANGE_RESTORE_FW_STATUS_SHADOW_SMOKE_WARNING, ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_READY],
        [ORANGE_RESTORE_FW_STATUS_EXECUTION_PLAN_READY, ORANGE_RESTORE_FW_STATUS_APPROVED_WAITING_EXECUTION],
    ];
}

/**
 * @return list<string>
 */
function orange_restore_fw_transition_global_targets(): array
{
    return [
        ORANGE_RESTORE_FW_STATUS_CANCELLED,
        ORANGE_RESTORE_FW_STATUS_FAILED,
        ORANGE_RESTORE_FW_STATUS_EXECUTION_CANCELLED,
        ORANGE_RESTORE_FW_STATUS_EXECUTION_FAILED,
        ORANGE_RESTORE_FW_STATUS_CUTOVER_READINESS_BLOCKED,
    ];
}

/**
 * @return list<string>
 */
function orange_restore_fw_transition_terminal_statuses(): array
{
    return [
        ORANGE_RESTORE_FW_STATUS_RESTORE_COMPLETED,
        ORANGE_RESTORE_FW_STATUS_ROLLBACK_COMPLETED,
        ORANGE_RESTORE_FW_STATUS_EXECUTION_COMPLETED,
        ORANGE_RESTORE_FW_STATUS_COMPLETED,
        ORANGE_RESTORE_FW_STATUS_CANCELLED,
        ORANGE_RESTORE_FW_STATUS_FAILED,
        ORANGE_RESTORE_FW_STATUS_EXECUTION_CANCELLED,
        ORANGE_RESTORE_FW_STATUS_EXECUTION_FAILED,
    ];
}

/**
 * Adjacency: from => list of allowed next statuses (always includes self).
 *
 * @return array<string, list<string>>
 */
function orange_restore_fw_transition_matrix(): array
{
    static $cache = null;
    if (is_array($cache)) {
        return $cache;
    }

    $matrix = [];
    foreach (orange_restore_fw_allowed_statuses() as $status) {
        $matrix[$status] = [$status];
    }

    $add = static function (string $from, string $to) use (&$matrix): void {
        if (!isset($matrix[$from])) {
            $matrix[$from] = [$from];
        }
        if (!in_array($to, $matrix[$from], true)) {
            $matrix[$from][] = $to;
        }
    };

    foreach (orange_restore_fw_transition_chains() as $chain) {
        for ($i = 0; $i < count($chain) - 1; $i++) {
            $add($chain[$i], $chain[$i + 1]);
        }
    }
    foreach (orange_restore_fw_transition_extra_edges() as $edge) {
        $add($edge[0], $edge[1]);
    }

    $globals = orange_restore_fw_transition_global_targets();
    $terminals = orange_restore_fw_transition_terminal_statuses();
    foreach (array_keys($matrix) as $from) {
        if (in_array($from, $terminals, true)) {
            continue;
        }
        foreach ($globals as $g) {
            $add($from, $g);
        }
    }

    $cache = $matrix;

    return $cache;
}

function orange_restore_fw_transition_is_allowed(string $from, string $to): bool
{
    if ($to === '') {
        return false;
    }
    if ($from === '' || $from === '0') {
        return $to === ORANGE_RESTORE_FW_STATUS_QUEUED;
    }
    if ($from === $to) {
        return true;
    }
    $matrix = orange_restore_fw_transition_matrix();
    $allowed = $matrix[$from] ?? null;
    if (!is_array($allowed)) {
        return false;
    }

    return in_array($to, $allowed, true);
}

function orange_restore_fw_assert_transition(string $from, string $to): void
{
    if (!orange_restore_fw_transition_is_allowed($from, $to)) {
        throw new RuntimeException('illegal_framework_status_transition:' . $from . '=>' . $to);
    }
}
