<style>
.uc-sec-form-grid,.uc-cat-form-grid,.uc-sub-form-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));grid-template-areas:"active active . . . . . . . . sort sort""slug slug slug slug slug slug dept dept dept dept dept dept""en en en en en en ar ar ar ar ar ar""hi hi hi hi hi hi fil fil fil fil fil fil";gap:14px 18px;direction:ltr;}
.uc-sec-form-grid .uc-sec-sort,.uc-cat-form-grid .uc-cat-sort,.uc-sub-form-grid .uc-sub-sort{grid-area:sort;justify-self:end;width:100%;}
.uc-sec-form-grid .uc-sec-active,.uc-cat-form-grid .uc-cat-active,.uc-sub-form-grid .uc-sub-active{grid-area:active;justify-self:start;width:100%;}
.uc-sec-form-grid .uc-sec-dept,.uc-cat-form-grid .uc-cat-dept,.uc-sub-form-grid .uc-sub-dept{grid-area:dept;}
.uc-sec-form-grid .uc-sec-slug,.uc-cat-form-grid .uc-cat-slug,.uc-sub-form-grid .uc-sub-slug{grid-area:slug;}
.uc-sec-form-grid .uc-sec-ar,.uc-cat-form-grid .uc-cat-ar,.uc-sub-form-grid .uc-sub-ar{grid-area:ar;}
.uc-sec-form-grid .uc-sec-en,.uc-cat-form-grid .uc-cat-en,.uc-sub-form-grid .uc-sub-en{grid-area:en;}
.uc-sec-form-grid .uc-sec-fil,.uc-cat-form-grid .uc-cat-fil,.uc-sub-form-grid .uc-sub-fil{grid-area:fil;}
.uc-sec-form-grid .uc-sec-hi,.uc-cat-form-grid .uc-cat-hi,.uc-sub-form-grid .uc-sub-hi{grid-area:hi;}
.uc-sec-form-grid label,.uc-sec-form-grid input,.uc-sec-form-grid select,.uc-cat-form-grid label,.uc-cat-form-grid input,.uc-cat-form-grid select,.uc-sub-form-grid label,.uc-sub-form-grid input,.uc-sub-form-grid select{direction:rtl;text-align:right;}
.uc-sec-form-grid #uc_sec_slug,.uc-cat-form-grid #uc_cat_slug,.uc-sub-form-grid #uc_sub_slug{text-align:right;direction:ltr;}
.uc-sec-form-grid #uc_sec_name_en,.uc-cat-form-grid #uc_cat_name_en,.uc-sub-form-grid #uc_sub_name_en{direction:ltr;text-align:right;}
.uc-sec-form-grid .uc-sec-sort.admin-sort-field-wrap,.uc-sec-form-grid .uc-sec-active.admin-sort-field-wrap,.uc-cat-form-grid .uc-cat-sort.admin-sort-field-wrap,.uc-cat-form-grid .uc-cat-active.admin-sort-field-wrap,.uc-sub-form-grid .uc-sub-sort.admin-sort-field-wrap,.uc-sub-form-grid .uc-sub-active.admin-sort-field-wrap{max-width:var(--admin-sort-field-max-w,220px);}
.uc-sec-form-grid #uc_sec_sort,.uc-sec-form-grid #uc_sec_active,.uc-cat-form-grid #uc_cat_sort,.uc-cat-form-grid #uc_cat_active,.uc-sub-form-grid #uc_sub_sort,.uc-sub-form-grid #uc_sub_active{margin-inline:0;display:block;width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:var(--radius-sm,10px);font-size:14px;line-height:calc(var(--input-min-h,36px) - 2px);min-height:var(--input-min-h,36px);height:var(--input-min-h,36px);max-height:var(--input-min-h,36px);padding-block:0;padding-inline:12px;}
.uc-sec-form-grid #uc_sec_department_id,.uc-sec-form-grid #uc_sec_name_ar,.uc-sec-form-grid #uc_sec_name_en,.uc-sec-form-grid #uc_sec_name_fil,.uc-sec-form-grid #uc_sec_name_hi,.uc-sec-form-grid #uc_sec_slug,.uc-cat-form-grid #uc_cat_section_id,.uc-cat-form-grid #uc_cat_name_ar,.uc-cat-form-grid #uc_cat_name_en,.uc-cat-form-grid #uc_cat_name_fil,.uc-cat-form-grid #uc_cat_name_hi,.uc-cat-form-grid #uc_cat_slug,.uc-sub-form-grid #uc_sub_category_id,.uc-sub-form-grid #uc_sub_name_ar,.uc-sub-form-grid #uc_sub_name_en,.uc-sub-form-grid #uc_sub_name_fil,.uc-sub-form-grid #uc_sub_name_hi,.uc-sub-form-grid #uc_sub_slug{margin-inline:0;display:block;width:100%;max-width:none;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:var(--radius-sm,10px);font-size:14px;line-height:1.4;min-height:var(--input-min-h,36px);padding:8px 12px;}
.uc-sec-form-grid #uc_sec_department_id,.uc-cat-form-grid #uc_cat_section_id,.uc-sub-form-grid #uc_sub_category_id{-webkit-appearance:none;appearance:none;background-color:#fff;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%2394a3b8' d='M2.75 4.25L6 7.55l3.25-3.3.65.64L6 8.82 2.1 4.9l.65-.65z'/%3E%3C/svg%3E");background-repeat:no-repeat;background-size:12px;background-position:left 12px center;padding-inline-end:32px;}
.uc-sec-form-grid input#uc_sec_sort::-webkit-outer-spin-button,.uc-sec-form-grid input#uc_sec_sort::-webkit-inner-spin-button,.uc-cat-form-grid input#uc_cat_sort::-webkit-outer-spin-button,.uc-cat-form-grid input#uc_cat_sort::-webkit-inner-spin-button,.uc-sub-form-grid input#uc_sub_sort::-webkit-outer-spin-button,.uc-sub-form-grid input#uc_sub_sort::-webkit-inner-spin-button{-webkit-appearance:none;margin:0;}
.uc-sec-form-grid input#uc_sec_sort,.uc-cat-form-grid input#uc_cat_sort,.uc-sub-form-grid input#uc_sub_sort{-moz-appearance:textfield;appearance:textfield;}
.uc-sec-form-grid #uc_sec_active,.uc-cat-form-grid #uc_cat_active,.uc-sub-form-grid #uc_sub_active{-webkit-appearance:none;appearance:none;background-color:#fff;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%2394a3b8' d='M2.75 4.25L6 7.55l3.25-3.3.65.64L6 8.82 2.1 4.9l.65-.65z'/%3E%3C/svg%3E");background-repeat:no-repeat;background-size:12px;background-position:left 12px center;padding-inline-end:32px;}
@media(max-width:860px){.uc-sec-form-grid,.uc-cat-form-grid,.uc-sub-form-grid{grid-template-columns:1fr;grid-template-areas:"sort""active""dept""slug""ar""en""fil""hi";}.uc-sec-form-grid .uc-sec-sort,.uc-sec-form-grid .uc-sec-active,.uc-cat-form-grid .uc-cat-sort,.uc-cat-form-grid .uc-cat-active,.uc-sub-form-grid .uc-sub-sort,.uc-sub-form-grid .uc-sub-active{justify-self:start;max-width:var(--admin-sort-field-max-w,220px);}}
.uc-table{border-collapse:collapse;width:100%;font-size:0.93rem;}
.uc-table th,.uc-table td{padding:10px;border-bottom:1px solid #f0f1f5;vertical-align:top;}
.uc-table thead th{border-bottom-color:#e8e9ec;text-align:right;}
.uc-table thead th:last-child{text-align:center;}
.uc-table tbody td:last-child{text-align:center;}
</style>
